<!-- Global APlayer -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css">
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js"></script>
<meting-js
  auto="https://music.163.com/#/playlist?id=648989969"
  list-folded="true"
  fixed="true"
  lrc-type="0">
</meting-js>
